// Medical symptom & body-part keywords for triage assessment (singular normalized)
export const symptomKeywords = [
  // General / systemic
  "fever",
  "high temperature",
  "chill",
  "rigor",
  "sweating",
  "fatigue",
  "weakness",
  "malaise",
  "unexplained weight loss",
  "unexplained weight gain",
  "night sweat",
  "dehydration",
  "loss of appetite",
  "excessive thirst",
  "excessive urination",
  "pain",
  "severe pain",
  "sudden pain",
  "fever with chill",
  "feeling unwell",
  "reduced activity",
  "poor oral intake",

  // Hair / scalp
  "hair",
  "scalp",
  "hair follicle",
  "hair loss",
  "hair thinning",
  "dandruff",
  "scalp itching",

  // Neurological
  "headache",
  "severe headache",
  "dizziness",
  "confusion",
  "memory problem",
  "loss of consciousness",
  "fainting",
  "difficulty speaking",
  "slurred speech",
  "facial drooping",
  "numbness",
  "tingling",
  "pins and needles",
  "tremor",
  "seizure",
  "blurred vision",
  "vision loss",
  "one-sided weakness",
  "balance problem",
  "difficulty walking",
  "drowsiness",
  "sensitivity to light",

  // Respiratory
  "cough",
  "shortness of breath",
  "difficulty breathing",
  "breathlessness",
  "shortness of breath at rest",
  "chest pain",
  "chest tightness",
  "chest discomfort",
  "wheezing",
  "coughing blood",
  "runny nose",
  "stuffy nose",
  "nasal congestion",
  "sore throat",
  "throat irritation",
  "loss of smell",
  "loss of taste",
  "fast breathing",
  "noisy breathing",
  "breathing worse when lying down",

  // Cardiovascular
  "palpitation",
  "rapid heartbeat",
  "heart racing",
  "high blood pressure",
  "low blood pressure",
  "heart attack",
  "leg swelling",
  "cold hand",
  "cold foot",
  "bluish lip",
  "bluish finger",

  // Gastrointestinal
  "nausea",
  "vomiting",
  "blood in vomit",
  "diarrhea",
  "constipation",
  "abdominal pain",
  "severe abdominal pain",
  "bloating",
  "heartburn",
  "blood in stool",
  "black stool",
  "stomach cramp",
  "gas",
  "indigestion",
  "difficulty swallowing",
  "food intolerance",

  // Urinary
  "painful urination",
  "burning urination",
  "frequent urination",
  "blood in urine",
  "urinary retention",
  "urinary incontinence",
  "reduced urine output",
  "strong smelling urine",

  // Musculoskeletal / injury
  "joint pain",
  "muscle pain",
  "body ache",
  "back pain",
  "lower back pain",
  "neck pain",
  "arm pain",
  "leg pain",
  "bone pain",
  "fracture",
  "injury",
  "fall",

  // Skin / allergic
  "skin rash",
  "itching",
  "hive",
  "dry skin",
  "skin redness",
  "warm skin",
  "skin peeling",
  "non healing wound",
  "easy bruising",
  "swelling",
  "swelling of face or lip",
  "skin infection",
  "fungal infection",
  "eye redness",
  "eye pain",

  // Psychiatric / sleep
  "anxiety",
  "depression",
  "irritability",
  "insomnia",
  "excessive sleepiness",
  "lethargy",
  "sudden behavior change",

  // Reproductive / sexual
  "vaginal bleeding",
  "abnormal menstrual bleeding",
  "pregnancy bleeding",
  "genital discharge",
  "pelvic pain",
  "penis pain",
  "testicular pain",
  "pain during sex",
  "erectile dysfunction",

  // Emergency
  "bleeding",
  "hemorrhage",
  "anaphylaxis",

  // Body parts (singular, user language)
  "head",
  "brain",
  "eye",
  "ear",
  "nose",
  "mouth",
  "tooth",
  "tongue",
  "throat",
  "tonsil",
  "neck",
  "jaw",
  "cheek",
  "sinus",

  "chest",
  "heart",
  "heart valve",
  "lung",
  "bronchus",
  "trachea",
  "diaphragm",
  "rib",

  "abdomen",
  "stomach",
  "esophagus",
  "liver",
  "gallbladder",
  "pancreas",
  "spleen",
  "intestine",
  "colon",
  "rectum",
  "appendix",
  "anus",

  "kidney",
  "ureter",
  "bladder",
  "urethra",

  "genital",
  "prostate",
  "ovary",
  "uterus",
  "cervix",
  "vagina",

  "spine",
  "shoulder",
  "arm",
  "elbow",
  "wrist",
  "hand",
  "finger",
  "hip",
  "pelvis",
  "leg",
  "thigh",
  "knee",
  "calf",
  "ankle",
  "foot",
  "toe",
  "bone",
  "bone marrow",
  "joint",
  "muscle",
  "tendon",
  "ligament",

  "skin",
  "nail",
  "lymph node",
  "blood vessel",
  "artery",
  "vein",
  "nerve",

  "thyroid",
  "adrenal gland",
  "pituitary gland"
];
